//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: System.Reflection.AssemblyVersion("1.0.0.92")]
[assembly: System.Reflection.AssemblyFileVersion("1.0.0.92")]
[assembly: System.Reflection.AssemblyInformationalVersion("feature/net35_port-9c0586b92a2aae47d46b380b5fde25a9e4b70b2d-20170407-105233")]


