//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: System.Reflection.AssemblyVersion("1.0.0.116")]
[assembly: System.Reflection.AssemblyFileVersion("1.0.0.116")]
[assembly: System.Reflection.AssemblyInformationalVersion("feature/log_file_target_dir-f66b5f095da2bf9da734837ba1646e108868fb52-20170424-113" +
    "410")]


