//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: System.Reflection.AssemblyVersion("1.0.0.84")]
[assembly: System.Reflection.AssemblyFileVersion("1.0.0.84")]
[assembly: System.Reflection.AssemblyInformationalVersion("develop-cb58724e18df10bef8d0a1a901d4902ddd05db5d-20170405-112302")]


