//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: System.Reflection.AssemblyVersion("1.0.0.95")]
[assembly: System.Reflection.AssemblyFileVersion("1.0.0.95")]
[assembly: System.Reflection.AssemblyInformationalVersion("develop-8f9d1d1a0e6582cc76ba8a67312efa8091ac7efe-20170410-112648")]


